//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApexaAdvisors.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ApexaAdvisors.Domain.Resources.CommonResource", typeof(CommonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address should be less than 255 characters..
        /// </summary>
        public static string Validations_AddressShouldBeLessThan255Characters {
            get {
                return ResourceManager.GetString("Validations_AddressShouldBeLessThan255Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advisor not found..
        /// </summary>
        public static string Validations_AdvisorNotFound {
            get {
                return ResourceManager.GetString("Validations_AdvisorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        public static string Validations_NameIsRequired {
            get {
                return ResourceManager.GetString("Validations_NameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name should be less than 255 characters..
        /// </summary>
        public static string Validations_NameShouldBeLessThan255Characters {
            get {
                return ResourceManager.GetString("Validations_NameShouldBeLessThan255Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone should be 8 digits.
        /// </summary>
        public static string Validations_PhoneShouldBe8Digits {
            get {
                return ResourceManager.GetString("Validations_PhoneShouldBe8Digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social identity number already exists.
        /// </summary>
        public static string validations_SinAlreadyExists {
            get {
                return ResourceManager.GetString("validations_SinAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social identity number is invalid.
        /// </summary>
        public static string Validations_SinIsInvalid {
            get {
                return ResourceManager.GetString("Validations_SinIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social identity number is required..
        /// </summary>
        public static string Validations_SinIsRequired {
            get {
                return ResourceManager.GetString("Validations_SinIsRequired", resourceCulture);
            }
        }
    }
}
